### ISSUE TITLE
Miscellaneous items from the playback's feedback

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/draft-iguide-bulkhead#38]
- [x] change Customer 1 to Customer1 or Customer_1 (Fixed in #43)

- [x] size of browser and editor to be the same (Fixed in #42)

- [x] add a link to enable mp feature from the step (Bulkhead, Bulkhead with Asynchronous, Fallback step) (Fixed in #44)

- [x] add Circuit Breaker to the relate guide (Fixed in #43)

- [x] update handleBulkheadException(); to handleException() (Fixed in #40)

- [x] update the word active chat sessions in the instructions to busy to cover hanging chat sessions

- [x] add a link to fallback method of circuit breaker in fallback step (Fixed in #44)

- [x] remove green button above browser (Fixed in #48)

- [x] update html page with new design from Murphy (Fixed in #52, #55, #56)

- [x] update error html page with design from Murphy (Fixed in #57)

- [x] update fallback html for scheduling with design from Murphy (Fixed in #66)
