### ISSUE TITLE
Noted items from team's playback

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/draft-iguide-bulkhead#70]
1. Background concepts:

- [x] Change to Explore how to prevent a failure from bringing down the entire system. (PR #73)
- [x] need link for MicroProfile and Fault Tolerance as in circuit breaker guide (PR #73)
- [x] add fallback definition (PR #73)
- [x] to be consistent either use you'll or you will across the paragraph (PR #73)
- [ ] need more detail explaining on semaphore approach, why we choose one over another? - move to issue#80
- [x] bold semaphore and threadpool  (PR #73)
- [x] check definition of bulkhead on  “can be sealed off” (PR #73)

2. Example scenario:
- [x] Change to The initial synchronous implementation of the VirtualFinancialAdvisor (PR #73)
- [x] Change to Request virtual financial advisor (PR #73)
- [x] Instruction: change to see failure after click on chat request button (PR #73)

3. Java Concurrency with Future and Executors:
- [x] code block everything with Future and Executor (PR #73)
- [ ] Instruction: causing it to overload and affect other microservices - expand by adding bringing down the site (Not really needed)
- [x] The initial on the chat in the browser loading problem (PR #69)
- [x] Shorten the sentence in the text holder next to the submit button (PR #69)

4. Adding Bulkhead annotation with Async
- [ ] explaining thread pool isolation, why it’s better to use the thread pool - move to issue#80
- [x] @Asynchronous need code block inside instruction (PR #73)
- [x] in the definition to mention best practice to use same value for value/waitingTaskQueue (PR #73)

5. Playground
- [x] Instruction: a virtual financial advisor (PR #73)
- [x] should we use dashboard here as well?? NO
- [x] add best practice about waitingTaskQueue (same as in Bulkhead with Async) (PR #73)

6. Fallback
- [x] a method link to open a new tab instead (PR #73)
- [x] open an issue in circuit breaker to link to bulkhead fallback class (issue #93)
- [x] Instruction: need to indicate Bulkhead exception is thrown before The fallback service will run to handle .... (PR #73)
- [x] handle submit button to display a thank you page, still disable backward/forward/refresh button (PR #71)

7. Dashboard: 
- [x] div delimiter  (PR #72)

8. Fix the browser height
- [x] Height difference in Java Concurrency with Future and Executor (PR #69)
- [X] Height difference when resizing to a narrower width (PR #74)

9. Change the instructions
 - [ ] Change the instruction: Let’s see/simulate 50 concurrent requests to work with the dashboard(PR #67) - move to issue#80

**Comment by dmorgant** [comment]
Question:   In the Adding Bulkhead annotation with Async step, should 'Future' and "Executors' (the things we are removing) be in code blocks also?
