### ISSUE TITLE
Todo items from stakeholder's playback

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/draft-iguide-bulkhead#80]
1.  Example scenario:
- [ ]  change to The initial naive synchronous implementation …

2. Java Concurrency:
- [ ] Link Future and Executors to java doc in openliberty.io (clickable)  future to do
- [ ] Using lamda expression - a little pop up to explain or tooltip to identify the lamda expression 
- [ ] In instruction: explicitly call out the VFA microservice runs out of CPU or memory
- [ ] In instruction: add a safeguard, as the VFA system slowly run 

3.  Instructions:
- [ ] remove the 97 customers?? change to just As more customer request chat sessions with.. and all 50 sessions are still busy..

4.  Adding @Asynchronous with @Bulkhead
- [ ] explaining counterForVFA
- [ ] move the scrollbar down to make the editor code more visible
- [ ] simplify to the code block to the end user by consolidate to just 2 blocks of method
- [ ] explicitly call out that @Asynchronous made it simplify the code

5.  Playground:
- [ ]  check with Emily on why it’s best practice to have value and waitingTaskQueue the same
- [ ]  change wording to number of active chat sessions
- [ ]  change to people icon instead of square
- [ ]  focus doesn’t go away?

6.  Great work! you’re done step:
- [ ] Summarize what you learned , add more content explaination, benefits of what you just done
